version: "3.8"
   
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=videojuegos
      - MYSQL_DATABASE=videojuegos
      - MYSQL_USER=videojuegos
      - MYSQL_PASSWORD=videojuegos
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3302:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db