# Generated by Django 3.1.6 on 2021-02-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Titulo'),
        ),
    ]
