# Generated by Django 3.1.6 on 2021-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0002_auto_20210218_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcio',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
