# Generated by Django 3.2 on 2021-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0003_auto_20210220_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
