# Generated by Django 3.2 on 2021-05-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options'),
        ('videojuego', '0004_videojuego_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_videojuego', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('titulo_videojuego', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.venta', verbose_name='Venta')),
            ],
        ),
    ]
