# Generated by Django 3.2 on 2021-05-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0005_auto_20210512_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_videojuego',
            field=models.IntegerField(verbose_name='ID_Videojuego'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='titulo_videojuego',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
