# Generated by Django 3.2 on 2021-04-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210318_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('permiso_usuario', 'usuario')]},
        ),
    ]
